apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"      # Active scraping Prometheus
        prometheus.io/path: "/metrics"    # Endpoint des métriques
        prometheus.io/port: "8081"        # Port d'écoute des métriques (doit correspondre au containerPort)
    spec:
      containers:
      - name: frontend
        image: aymar100/frontend-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: myapp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8081
    nodePort: 30005
  selector:
    app: frontend
