apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node_exporter'
        static_configs:
          - targets:
              - '10.244.0.3:9100'
              - '10.244.1.2:9100'
              - '10.244.2.3:9100'

      - job_name: 'cadvisor'
        static_configs:
          - targets:
              - '10.244.0.4:8080'
              - '10.244.1.8:8080'
              - '10.244.2.7:8080'
